env: local
http:
  host: http://127.0.0.1
  port: 8090
security:
  jwt:
    key: 1234
data:
  mysql:
    user: root:123123@tcp(127.0.0.1:3306)/chess?charset=utf8mb4&parseTime=True&loc=Local

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30              # 日志文件最多保存多少个备份
  max_age: 7                   #  文件最多保存多少天
  max_size: 1024               #  每个日志文件保存的最大尺寸 单位：M
  compress: true               # 是否压缩