// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"chess/internal/handler"
	"chess/internal/repository"
	"chess/internal/server"
	"chess/internal/service"
	"chess/pkg/log"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	db := repository.NewDb()
	handlerHandler := handler.NewHandler(logger, db)
	serviceService := service.NewService(logger)
	repositoryRepository := repository.NewRepository(logger, db)
	rankRepository := repository.NewRankRepository(repositoryRepository)
	rankService := service.NewRankService(serviceService, rankRepository)
	rankHandler := handler.NewRankHandler(handlerHandler, rankService)
	engine := server.NewServerHTTP(logger, rankHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRepository, repository.NewRankRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewRankService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewRankHandler)
